quarkus.index-dependency.rimfrost-handlaggning-adapter.group-id=se.fk.rimfrost.framework.handlaggning
quarkus.index-dependency.rimfrost-handlaggning-adapter.artifact-id=rimfrost-framework-handlaggning-adapter
