quarkus.index-dependency.rimfrost-handlaggning-adapter.group-id=se.fk.rimfrost.framework.handlaggning
quarkus.index-dependency.rimfrost-handlaggning-adapter.artifact-id=rimfrost-framework-handlaggning-adapter

application.config.path=src/main/resource/config.yaml

# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

#Incoming
mp.messaging.incoming.regel-requests.connector=smallrye-kafka
mp.messaging.incoming.regel-requests.auto.offset.reset=earliest
mp.messaging.incoming.regel-requests.value.deserializer=se.fk.rimfrost.framework.regel.presentation.kafka.RegelRequestDeserializer

#Outgoing
mp.messaging.outgoing.regel-responses.connector=smallrye-kafka
mp.messaging.outgoing.regel-responses.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
