name: Validate config.yaml

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Extract workflow ref
        id: get-ref
        run: echo "ref=${GITHUB_WORKFLOW_REF##*@}" >> $GITHUB_OUTPUT

      - name: Checkout rimfrost-framework-regel
        uses: actions/checkout@v4
        with:
          repository: Forsakringskassan/rimfrost-framework-regel
          ref: ${{ steps.get-ref.outputs.ref }}
          path: framework-regel

      - name: Validate config.yaml against regel schema
        run: |
          pip install check-jsonschema==0.37.3
          check-jsonschema \
            --schemafile framework-regel/src/main/resources/schema/regel_schema.yaml \
            src/main/resources/config.yaml
